//#define HMM_BLOCK_HEIGHT 1
//#define MAX_COPY_NUM 4
//#define HMM_STATES 1024
//#define HMM_GRID_WIDTH HMM_BLOCK_WIDTH*HMM_BLOCK_WIDTH
//#define HMM_GRID_HEIGHT 1
//#define HMM_OBSERVATIONS 41263
//#define HMM_OBSERVATIONS 100
//#define HMM_OBS_BLOCK_WIDTH 32
#define HMM_SMALL 1e-10
#define HMM_STATE_BLOCK_WIDTH 512
#define HMM_OBS_BLOCK_WIDTH 512
#define HMM_TRANSITION_LARGE 1e8
//#define HMM_TRANSITION_LARGE 1e4
// MAXIMUM TOTAL BLOCK WIDTH FOR NVS 290 IS 65536
